### ISSUE TITLE
Contact dalcinl@gmail.com not responsible

### ISSUE THREAD

**Issue by fkbreitl** [scipy/scipy.org#114] opened 2015-10-09 18:03 UTC
The contact: dalcinl@gmail.com listed at https://planet.scipy.org/ is not responsible.
Please update. I received this email:

-------- Forwarded Message --------
Subject: 	Fwd: http://wiki.scipy.org/Cookbook Forbidden
Date: 	Tue, 6 Oct 2015 11:41:22 +0300
From: 	Lisandro Dalcin <dalcinl@gmail.com>
To: 	Frank Breitling <fbreitling@aip.de>

Dear Frank, I got two emails in the forward below, they may help you
to fix the issues in the scipy.org site.

---------- Forwarded message ----------
From: Brian Granger <ellisonbg@gmail.com>
Date: 2 October 2015 at 22:01
Subject: Re: http://wiki.scipy.org/Cookbook Forbidden
To: Lisandro Dalcin <dalcinl@gmail.com>

Hi!

I think it is these folks:

Allen Parker <aparker@enthought.com> with a Cc to Didrik Pinte
<dpinte@enthought.com>

Let me know if that doesn't work.

Cheers,

Brian

On Wed, Sep 30, 2015 at 12:56 PM, Lisandro Dalcin <dalcinl@gmail.com> wrote:
> Dear Brian, how are you? I got the complaint I'm forwarding.
>
> Basically, if you go to http://scipy.org/ and then you click in the
> top-right icon (Blog), then you should be redirected to
> https://planet.scipy.org/ , but the mpi4py docs show up. I have no
> idea who is the admin of scipy.org these days, any tip about how to
> proceed to get this fixed?
>
>
>
>
> ---------- Forwarded message ----------
> From: Frank Breitling <fbreitling@aip.de>
> Date: 30 September 2015 at 14:16
> Subject: Re: http://wiki.scipy.org/Cookbook Forbidden
> To: Lisandro Dalcin <dalcinl@gmail.com>
>
>
> Your name is the first thing that appears at
>
> https://planet.scipy.org/
>
> You get there when you click on Blogs from (top right) on
>
> http://scipy.org/
>
> Then you should get this changed as soon as possible.
>
>
>
> On 29.09.2015 13:15, Lisandro Dalcin wrote:
>>
>> On 28 September 2015 at 17:02, Frank Breitling <fbreitling@aip.de> wrote:
>>>
>>> Alright, but then why is your name listed instead of the admin?
>>> Maybe you should have somebody change this.
>>>
>>
>> Where is my name listed? I never had admin access to that server, I
>> only had user-level access to the subdomain http://mpi4py.scipy.org/,
>> which I'm no longer using and goes down time to time. That subdomain
>> is there just to host documentation about one of my projects, but I
>> never handled the "wiki" subdomain.
>>
>> Did you try to send an email to the scipy mailing list?
>> http://www.scipy.org/scipylib/mailing-lists.html
>>
>
>
>
> --
> Lisandro Dalcin
> ============
> Research Scientist
> Computer, Electrical and Mathematical Sciences & Engineering (CEMSE)
> Numerical Porous Media Center (NumPor)
> King Abdullah University of Science and Technology (KAUST)
> http://numpor.kaust.edu.sa/
>
> 4700 King Abdullah University of Science and Technology
> al-Khawarizmi Bldg (Bldg 1), Office # 4332
> Thuwal 23955-6900, Kingdom of Saudi Arabia
> http://www.kaust.edu.sa
>
> Office Phone: +966 12 808-0459

--
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by pv** [comment] 2015-10-09 19:00
Duplicate of gh-102

**Closed by pv** 2015-10-09 19:00 UTC
