### ISSUE TITLE
Planet SciPy rendering issue

### ISSUE THREAD

**Issue by gfunch** [scipy/scipy.org#518] opened 2023-05-20 13:19 UTC
As of 20230520, the Planet SciPy webpage shows the following:

```
Updated 2023-05-20 09:09:23 UTC. All blog posts are by third parties, not scipy.org. The posts are aggregated here by an automated mechanism, [staticplanet](https://github.com/pv/staticplanet/). Contact: [issue tracker](https://github.com/scipy/scipy.org/issues). 

Failed to fetch:

    http://acsgsoc15.wordpress.com/feed/atom
    http://andy.terrel.us/feeds/scipy-tag.rss.xml
    http://blog.filipesaraiva.info/?feed=rss2&amp;tag=planet-scipy
    http://blog.fperez.org/feeds/posts/default
    http://blog.jarrodmillman.com/feeds/posts/default
    http://conference.scipy.org/feeds/all.atom.xml
    http://cournape.wordpress.com/feed/atom
    http://droettboom.com/feeds/all.atom.xml
    http://enthought.com/blog/feed/
    http://euphoricjenny.blogspot.com/feeds/posts/default/-/GSoC/?alt=rss
    http://fa.bianp.net/blog/feed/
    http://fortrancython.wordpress.com/feed/atom
    http://fuhrysoc.blogspot.com/feeds/posts/default
    http://gael-varoquaux.info/feeds/programming.atom.xml
    http://geologyandpython.com/feeds/all.rss.xml
    http://ilovesymposia.com/rss.xml
    http://issamlaradji.blogspot.com/feeds/posts/default?alt=rss
    http://ivory.idyll.org/blog/feeds/all.atom.xml
    http://jakevdp.github.io/feeds/all.atom.xml
    http://jmetzen.github.io/feeds/python.rss
    http://jpktd.blogspot.com/feeds/posts/default
    http://maheshakya.github.io/feed.xml
    http://manojbits.wordpress.com/category/scikit-learn/feed/atom
    http://markflorisson.wordpress.com/feed/atom
    http://matthewrocklin.com/blog/feed.scipy.xml
    http://metarabbit.wordpress.com/tag/python/feed/atom
    http://mfitzp.io/feeds/python.tag.atom.xml
    http://neuralensemble.blogspot.com/feeds/posts/default
    http://nipy.github.io/blog/feeds/all.rss.xml
    http://nmayorov.wordpress.com/tag/gsoc/feed/atom
    http://ondrejcertik.blogspot.com/feeds/posts/default/-/scipy
    http://openopt.blogspot.com/feeds/posts/default
    http://pandasplotting.blogspot.com/feeds/posts/default
    http://pdebuyl.be/feeds/scipy.tag.atom.xml
    http://peekaboo-vision.blogspot.com/feeds/posts/default
    http://physionconsulting.blogspot.com/feeds/posts/default/-/scipy
    http://pirsquared.org/blog/feeds/all.atom.xml
    http://prabhuramachandran.blogspot.com/feeds/posts/default
    http://pycloud.blogspot.com/feeds/posts/default/-/scipy
    http://pythonimaging.blogspot.com/feeds/posts/default
    http://pythonxynews.blogspot.de/feeds/posts/default
    http://sagemath.blogspot.com/feeds/posts/default
    http://samspythonblogspot.blogspot.com/feeds/posts/default
    http://scipy2010.blogspot.com/feeds/posts/default
    http://scipystats.blogspot.com/feeds/posts/default
    http://scipystatsimprovements.blogspot.mx/feeds/posts/default?alt=rss
    http://surya-gsoc2013.blogspot.in/feeds/posts/default
    http://sympy.blogspot.com/feeds/posts/default
    http://technicaldiscovery.blogspot.com/feeds/posts/default
    http://travisvaught.blogspot.com/feeds/posts/default/-/python
    http://twiecki.github.io/atom.xml
    http://vcansimplify.wordpress.com/tag/gsoc/feed/atom
    http://www.laurentluce.com/posts/tag/scipy/feed/
    http://www.leouieda.com/rss.xml
    http://www.logilab.org/bookmark/9844/follow
    http://www.numfocus.org/feed
    http://www.randalolson.com/tag/python/feed/
    http://www.spyder-ide.org/blog/feed.xml
    http://xuewei4d.github.io/feed.xml
    https://acoular.github.io/blog/feed.xml
    https://ai-pool.com/feed_article.xml
    https://blog.scikit-learn.org/feed.xml
    https://jbencook.com/feed.xml
    https://labs.quansight.org/rss.xml
    https://mentat.za.net/blog/tags/python/atom.xml
    https://neptune.ml/feed
    https://pav.iki.fi/blog.xml
    https://rgommers.github.io/index.xml
    https://www.anaconda.com/blog/feed/
    https://www.listendata.com/feeds/posts/default/-/Python
    https://www.nbshare.io/feeds/all.atom.xml
```

**Comment by lucascolley** [comment] 2024-01-07 21:19
I can't reproduce at https://planet.scipy.org/. Closing, but let us know if this is still happening for you.

**Comment by lucascolley** [comment] 2024-01-07 21:20
Nevermind, I scrolled down and see

```
Failed to fetch:

http://andy.terrel.us/feeds/scipy-tag.rss.xml
http://blog.fperez.org/feeds/posts/default
http://jmetzen.github.io/feeds/python.rss
http://twiecki.github.io/atom.xml
http://www.leouieda.com/rss.xml
http://www.logilab.org/bookmark/9844/follow
http://www.randalolson.com/tag/python/feed/
https://ai-pool.com/feed_article.xml
https://jbencook.com/feed.xml
https://pav.iki.fi/blog.xml
https://www.nbshare.io/feeds/all.atom.xml
```

**Comment by lucascolley** [comment] 2024-08-15 22:09
Closing as it looks like Planet SciPy is likely to stay down in the future - gh-560

**Closed by lucascolley** 2024-08-15 22:09 UTC
