### ISSUE TITLE
Latex output is broken

### ISSUE THREAD

**Issue by mattip** [scipy/scipy.org#264] opened 2018-08-16 15:39 UTC
First reported on numpy/numpy#11753. Our `conf.py` is set up to use latex tools to create images from latex input strings. This works find on [numpy.org](http://www.numpy.org/devdocs/reference/arrays.ndarray.html?highlight=internal#internal-memory-layout-of-an-ndarray) but not on [scipy.org](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray). It is not clear to me where the output from running the install scripts goes, on the NumPy repo there is a circleci job to build the documentation. Perhaps the latex tools are missing from the machine that builds, i.e. can someone run `dvisvgm` on the build machine and see that the executable is runnable there? Should we add a check for the command line tools to the Makefile and fail if they do not exist?

**Comment by pv** [comment] 2018-08-16 16:25
I think the documentation files are typically built by the release manager of the release, on their own machine. A point that could be systematized, perhaps.

**Comment by rgommers** [comment] 2018-10-20 04:00
https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray looks fine now. I'm unclear on exactly what the problem is/was.

and yes, I usually build the numpy docs for a new release. the issue that is no longer present seems to have been with the numpy docs hosted on docs.scipy.org. so the right issue tracker is the numpy one. so I will close this; follow-up discussion can be done at the still open https://github.com/numpy/numpy/issues/11753 (I'll comment there)

**Closed by rgommers** 2018-10-20 04:00 UTC
